[package]
name = "sign_ur_code"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argon2 = "0.5.3"
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.54", features = ["derive"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core", "digest", "zeroize"] }
eframe = "0.33.3"
hex = "0.4.3"
rand = "0.8.5"
rfd = "0.17.1"
rpassword = "7.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
zeroize = { version = "1.8.2", features = ["derive"] }
